### PR TITLE
Filter letters and special chars

### LINKED ISSUE #320: Exchnage row: if enter letters, if crashes Decimal error
image

### PR DESCRIPTION
**Pull request by Janaka-Steph**
It fixes #320 

Please review @tiero

### CODE REVIEW

File: src/components/ExchangeRow/index.tsx [hunk 1]
```diff
@@ -258,11 +258,11 @@ const ExchangeRow: React.FC<ExchangeRowInterface> = ({
         val = Number(e.detail.value).toFixed(MAX_DECIMAL_DIGITS);
       }
       // Set
-      setAmount(val);
-      onChangeAmount(val);
+      setAmount(val === '' ? '0' : val);
```
Comment (tiero) [inline src/components/ExchangeRow/index.tsx:261]: better create a function `sanitizeValue` ?
